In [91]:
import numpy as np
import tensorflow as tf
from pandas.io.parsers import read_csv
print("TensorFlow Version: %s" % tf.__version__)

TensorFlow Version: 2.0.0


In [92]:
data = read_csv('price data.csv', sep=',')

xy = np.array(data, dtype=np.float32)

x_data = xy[:, 1:-1]
y_data = xy[:, [-1]]

In [93]:
data

year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
0     20100101     -4.9    -11.0      0.9       0.0      2123
1     20100102     -3.1     -5.5      5.5       0.8      2123
2     20100103     -2.9     -6.9      1.4       0.0      2123
3     20100104     -1.8     -5.1      2.2       5.9      2020
4     20100105     -5.2     -8.7     -1.8       0.7      2060
...        ...      ...      ...      ...       ...       ...
2917  20171227     -3.9     -8.0      0.7       0.0      2865
2918  20171228     -1.5     -6.9      3.7       0.0      2884
2919  20171229      2.9     -2.1      8.0       0.0      2901
2920  20171230      2.9     -1.6      7.1       0.6      2901
2921  20171231      2.1     -2.0      5.8       0.4      2901

[2922 rows x 6 columns]

In [94]:
x_data

array([[ -4.9, -11. ,   0.9,   0. ],
       [ -3.1,  -5.5,   5.5,   0.8],
       [ -2.9,  -6.9,   1.4,   0. ],
       ...,
       [  2.9,  -2.1,   8. ,   0. ],
       [  2.9,  -1.6,   7.1,   0.6],
       [  2.1,  -2. ,   5.8,   0.4]], dtype=float32)

In [95]:
y_data

array([[2123.],
       [2123.],
       [2123.],
       ...,
       [2901.],
       [2901.],
       [2901.]], dtype=float32)

In [103]:
# Weights
tf.random.set_seed(2020)
W = tf.Variable(tf.random.normal([4, 1], mean=0.0))
b = tf.Variable(tf.random.normal([1], mean=0.0))

# Learning Rate
learning_rate = 0.000005

# Hypothesis and Prediction Function
def predict(X):
    return tf.matmul(X, W) + b

# Training
for i in range(100000+1):

    with tf.GradientTape() as tape:
        cost = tf.reduce_mean(tf.square(predict(x_data) - y_data))
        W_grad, b_grad = tape.gradient(cost, [W, b])

    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 500 == 0:
        print("#%s \t cost: %s" % (i, cost.numpy()))

#0 	 cost: 12354863.0
#500 	 cost: 4189053.0
#1000 	 cost: 3783544.8
#1500 	 cost: 3466804.2
#2000 	 cost: 3217688.2
#2500 	 cost: 3021284.2
#3000 	 cost: 2866195.0
#3500 	 cost: 2743596.5
#4000 	 cost: 2646612.2
#4500 	 cost: 2569847.5
#5000 	 cost: 2509059.2
#5500 	 cost: 2460904.0
#6000 	 cost: 2422739.2
#6500 	 cost: 2392477.2
#7000 	 cost: 2368468.5
#7500 	 cost: 2349408.5
#8000 	 cost: 2334264.5
#8500 	 cost: 2322219.0
#9000 	 cost: 2312627.5
#9500 	 cost: 2304975.8
#10000 	 cost: 2298860.2
#10500 	 cost: 2293961.0
#11000 	 cost: 2290024.0
#11500 	 cost: 2286848.2
#12000 	 cost: 2284275.8
#12500 	 cost: 2282180.0
#13000 	 cost: 2280462.2
#13500 	 cost: 2279042.5
#14000 	 cost: 2277860.2
#14500 	 cost: 2276865.0
#15000 	 cost: 2276018.0
#15500 	 cost: 2275288.5
#16000 	 cost: 2274651.8
#16500 	 cost: 2274088.8
#17000 	 cost: 2273584.0
#17500 	 cost: 2273125.2
#18000 	 cost: 2272703.0
#18500 	 cost: 2272310.2
#19000 	 cost: 2271940.2
#19500 	 cost: 2271588.5
#20000 	 cost: 2271251.

In [107]:
W

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float32, numpy=
array([[ -35.976414],
       [-180.30727 ],
       [ 259.114   ],
       [  39.170166]], dtype=float32)>

In [108]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([191.46692], dtype=float32)>

In [131]:
#predict model
avg_temp = float(2.0)
min_temp = float(-2.1)
max_temp = float(5.8)
rain_fall = float(0.4)

In [132]:
data = np.array(([[avg_temp,min_temp,max_temp,rain_fall]]), dtype=np.float32)

In [133]:
data

array([[ 2. , -2.1,  5.8,  0.4]], dtype=float32)

In [134]:
predict(data).numpy()

array([[2016.6887]], dtype=float32)